name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
      name: Go build
      runs-on: ubuntu-latest
      steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0
        with:
          version: v1.61.0
          args: --timeout 10m -v -c .golangci.yml
